package com.assetflow.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * Payload for registering or updating an asset.
 * assetTag is intentionally excluded - it is auto-generated by the service.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AssetDTO {
    private String name;
    private Long categoryId;
    private String serialNumber;
    private LocalDate acquisitionDate;
    private BigDecimal acquisitionCost;
    private String condition;
    private String location;
    private Long departmentId;
    private boolean sharedBookable;
    private String photoUrl;
}
