spring.application.name=assetflow-backend

# ===============================
# MYSQL DATABASE CONFIGURATION
# ===============================

spring.datasource.url=jdbc:mysql://localhost:3306/assetflow
spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false


# ===============================
# FLYWAY CONFIGURATION
# ===============================

# Disable because you already imported the SQL manually in XAMPP MySQL
spring.flyway.enabled=false


# ===============================
# JWT CONFIGURATION
# ===============================

jwt.secret=${JWT_SECRET:change-this-secret-in-production-please-32bytes+}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}


# ===============================
# SERVER
# ===============================

server.port=8080